project_id = "peljgdpjaqwygnjcnvln"

[functions.create-order]
verify_jwt = false

[functions.check-order-status]
verify_jwt = false

[functions.pix-webhook]
verify_jwt = false

[functions.admin-orders]
verify_jwt = false
